### ISSUE TITLE
Some contents needed to be updated on "Introduction to using GBIF-mediated data"

### ISSUE THREAD

**Issue by melissa0520** [gbif/training#17]
- Issues and flags
   - [Country centroids](https://training.gbif-uat.org/en/data-use/data-quality#country-centroids): Marie mentioned in the DU workshop last year that it will be possible to filter non-centroid coordinates on both GBIF.org and API, but I am not sure whether if it is available now.
   - [Establishment Means](https://training.gbif-uat.org/en/data-use/data-quality#establishment-means): The vocabulary terms are already updated on GBIF.org filter.
<img width="834" alt="image" src="https://github.com/user-attachments/assets/b69e3a96-03bb-418b-a9cf-db2bcf0c7d54">

**Comment by jhnwllr** [comment]
[Country centroids](https://training.gbif-uat.org/en/data-use/data-quality#country-centroids): Marie mentioned in the DU workshop last year that it will be possible to filter non-centroid coordinates on both GBIF.org and API, but I am not sure whether if it is available now.

Yes it's possible now. 

https://www.gbif.org/occurrence/search?advanced=1&occurrence_status=present&distance_from_centroid_in_meters=2000,*

**Comment by jhnwllr** [comment]
![image](https://github.com/user-attachments/assets/d3cf16a9-32cf-4e55-8c54-77ff2b628a35)

**Comment by jhnwllr** [comment]
You can also get the occurrence records that are close to centroids by using "less than or equal to" 

![image](https://github.com/user-attachments/assets/b91a442c-ad0e-42c7-b0f7-4de21e877ef3)

**Comment by melissa0520** [comment]
Thanks John! And I also updated this in my slides.
